set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @catppuccin_flavor 'macchiato'

run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g mouse on
set -g cursor-colour white

set -s escape-time 16
set -g focus-events on
set -s set-clipboard on

set-option -gw xterm-keys on
set-option -gw mode-keys vi

set -s extended-keys on
set -as terminal-features 'tmux*:extkeys'

#set -g default-terminal "screen-256color"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# remap prefix from 'C-b' to 'C-a'
#unbind C-b
#set-option -g prefix C-a
#bind C-a send-prefix

# Start window and pane numbering at 1
set -g base-index 1
set -g pane-base-index 1

set -g clock-mode-style 12

set -ga word-separators ",│`|:\"' ()[]{}<>"

set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
#set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

bind \\ split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'pbcopy'
bind -T copy-mode-vi 'J' send -X halfpage-down
bind -T copy-mode-vi 'K' send -X halfpage-up

#bind-key M choose-tree -Zw "join-pane -t '%%'"
#bind-key C-m choose-tree -Zs "join-pane -t '%%'"

set -g bell-action none
set -g visual-bell off

set-option -g history-limit 20000

set -g @thumbs-command 'tmux set-buffer -- {} && echo -n {} | pbcopy'
set -g @thumbs-contrast 1
set -g @thumbs-regexp-1 '[a-z0-9\.]+@[a-z]+\.(?:com|net|org|edu|io)' # Match emails
set -g @thumbs-regexp-2 '[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:' # Match Mac Addresses
set -g @thumbs-regexp-3 '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' # Match IP Addresses
set -g @thumbs-regexp-4 '[a-f0-9]{8,64}' # Match arbitrary hashes
set -g @thumbs-regexp-5 'Vlan\d+' # match Vlan interface on network devices
set -g @thumbs-regexp-6 "Vlan\\d+" # alternative method of defining regexp
set -g @thumbs-regexp-7 Vlan\\d+ # alternative method of defining regexp

unbind r
bind r source-file ~/.tmux.conf

bind -n C-M-l send-keys C-l

bind-key C-u copy-mode -u

# Popup windows
bind g display-popup -E -w 80% -h 80% -d '#{pane_current_path}' "lazygit"
bind t display-popup -E -w 60% -h 60% -d '#{pane_current_path}'

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Renaming
set-option -g automatic-rename on
set-option -g automatic-rename-format "#{b:pane_current_path}: #{pane_current_command}"
set-option -g allow-rename off
set-option -g renumber-windows on

set -g status-position top
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{?pane_in_mode,#[fg=#{@thm_crust}]#[bg=#{@thm_blue}] COPY #[default] ,}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

set -g @catppuccin_window_status_style "slanted"

set -g @catppuccin_window_text " #{?#{==:#{window_name},#{automatic-rename-format}},#{b:pane_current_path}: #{pane_current_command},#{window_name}}"
set -g @catppuccin_window_current_text " #{?#{==:#{window_name},#{automatic-rename-format}},#{b:pane_current_path}: #{pane_current_command},#{window_name}}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

