#!/bin/sh
# 
# The status bar
# 

alias echo='echo -n'
echo '{ "version": 1 }'
echo '['
echo '[]'

# Array begin
ARB=",[ "

# Array end
ARE=" ]"

# Full text begin
TEX="{ \"full_text\": \""

# Full text end
END="\" },"

# Begin
while true;
do
    # Date
    #echo ",[ { \"full_text\": \"$(date)\" } ]"
    
	echo "$ARB"
	# Beg Content
	
	echo "$TEX $(date) $END"
    #echo "$TEX test $END"

	# End Content
	echo "$ARE"
	sleep 1
done
