#
# Configuration containing file lists
#

# REQUIRED, but can be changed
SaveToLocation: files/

# Print the contents of the `reminders.rst` file after
# everything's copied
Reminders: False

# Remember: if SaveAs is not specified, it will use the
# name of the parent element
#
# Note: Tilde (~) is resolved as the home directory on
# Windows
vimrc:
    LocationLinux: ~/.vimrc
    LocationWin: ~/_vimrc
    LocationWork: M:/_vimrc_testing
    AdditionalFunction: vimrc

vim:
    Location: ~/.vim
    LocationWin: ~/vimfiles
    LocationWork: M:/vimfiles_testing
    #AdditionalFunction: vim
    Ignore:
        - 'bundle'
        - 'tags'
        - 'view'

xinitrc:
    LocationLinux: ~/.xinitrc

fonts.conf:
    LocationLinux: ~/.fonts.conf

i3:
    LocationLinux: ~/.i3
    Confirm: True

fish:
    LocationLinux: ~/.config/fish
    Confirm: True
    Ignore:
        - 'fish_history'
        - 'fish_read_history'
