#!/usr/bin/env bash
#

cat filter.txt |
  awk '
  # Remove blank lines, comments, and lines starting with "-" 
  $0 !~ "^(#|-)" && NF { 
    print substr($2, 2) 
  }' \
  | xargs -I '{}' diff -aurw --color=always ./dotfiles/{} $HOME/'{}' 2> /dev/null

