#
# Configuration containing file lists
#

# Unconditionally delete these:
Delete:
    - 'README.rst'
    - 'dotfiles_config.yml'
    - 'fix_dotfiles.py'
    - 'doc'

Windows:
    KeepAll: False

    .vimrc:
        Keep: True
        MoveTo: ~/_vimrc

    .vim:
        Keep: True
        MoveTo: ~/vimfiles

Work:
    KeepAll: False

    .vimrc:
        Keep: True
        MoveTo: M:/_vimrc

    .vim:
        Keep: True
        MoveTo: M:/vimfiles

Linux:
    KeepAll: True
