#!/usr/bin/env bash

backup_dir="_local-backup/$(date '+%Y-%m-%d_%H-%M-%S')"
mkdir -p "$backup_dir"

rsync -avh \
  --prune-empty-dirs \
  --filter="merge ./filter.txt" \
  $HOME/ \
  "./$backup_dir/"

rsync -avh \
  --prune-empty-dirs \
  --filter="merge ./filter.txt" \
  ./dotfiles/ \
  $HOME/

echo "\nIf you're unsure about how this sync went, run /reconcile-backup in Claude Code"
