#!/usr/bin/env bash

mkdir -p _local-backup

rsync -avh \
  --prune-empty-dirs \
  --filter="merge ./filter.txt" \
  _local-backup/ \
  $HOME/

rsync -avh \
  --prune-empty-dirs \
  --filter="merge ./filter.txt" \
  ./dotfiles/ \
  $HOME/
